### ISSUE TITLE
Criação da home

### ISSUE THREAD

**Issue by palavrinha** [palavrinha/palavrinha.github.io#1]
https://www.figma.com/file/ogEw3S9t9LQH4W0vuOEFDG/SITE---palavrinha2?node-id=11%3A163

**Comment by palavrinha** [comment]
![image](https://user-images.githubusercontent.com/90541780/134992695-f6a2af0a-75f1-4372-b291-3f69f65f9828.png)

**Comment by LumaSchwantes** [comment]
- 1º slide (foto das duas meninas lendo, fundo azul, logo do Palavrinha):
     > Diminuir o tamanho da fonte do texto corrido, para que não fique apertado. Se for possível, colocar parecido com o que tá no Figma, mesmo que o tamanho da fonte fique menor. O importante é a aparência do parágrafo. Uma coisa que é bom evitar são as viúvas, que são essas palavras que ficam sozinhas na última linha de algum parágrafo.
     > Fazer a frase "saiba mais sobre nós" caber dentro do retângulo (amarelo) que indica botão. Acredito que diminuindo a fonte caiba, ou então aumentando o retângulo. Como é um botão acho melhor o texto ficar em uma linha só;
     > Retirar o espaçamento antes do parágrafo. Deixar o mesmo alinhamento para o parágrafo todo.

- 2º slide (homem lendo para bebê, fundo amarelo):
     > Alinhar o título "comunicação infantil" à direita e ao parágrafo de texto corrido;
     > Diagramar o texto corrido de forma a que a palavra "falar" não fique sozinha na última linha (viúva). Se for necessário, pode diminuir um pouco o tamanho da fonte.

- 3º slide (meninas desenhando, fundo verde):
     > Diminuir a entrelinha do título "Como ajudar a criança?";
